version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["9d:9c:53:eb:fa:a4:83:81:a1:9b:45:e7:01:e9:4b:24"] # You can get this ID in the section where you registered the SSH Key
        
        # install the dependencies needed for your playbook
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible 
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory.txt playbook.yml

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
      